
server:
  port : 8081

# CHAT-GPT configuration properties
openai:
  api:
    url: ${GPT_API_URL:https://api.openai.com/v1/chat/completions}
    key: ${OPENAI_API_KEY:1}
    model: ${GPT_MODEL:gpt-3.5-turbo}


logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

clients:
  calendar_manager:
    url: ${CALENDAR_MANAGER_URL:http://localhost:8080}